#! /bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch
# Description:       Starts elasticsearch
### END INIT INFO

echo $ES_HOME
ES_MIN_MEM=128m
ES_MAX_MEM=256g
DAEMON=$ES_HOME/bin/elasticsearch
NAME=elasticsearch
DESC=elasticsearch
PID_FILE=/var/run/$NAME.pid
LOG_DIR=$ES_LOG_DIR
DATA_DIR=$ES_DATA_DIR
WORK_DIR=/tmp/$NAME

$ES_HOME/bin/elasticsearch -Des.path.home=$ES_HOME -Des.path.logs=$LOG_DIR -Des.path.data=$DATA_DIR -Des.path.work=$WORK_DIR
